api/urls.py
from django.urls import path
from . import views

app_name = 'api'
urlpatterns = [
    # update to cancel transaction entry
    path('v1/transaction/cancel/<str:transaction_id>', views.Transaction.cancel, name='api-cancel_transation'),
    path('v1/transaction/void/<str:transaction_id>', views.Transaction.void_transaction, name='api-void_transation'),
    path('v1/transaction/unvoid/<str:transaction_id>', views.Transaction.unvoid_transaction, name='api-unvoid_transation'),
    path('v1/transaction/report/<str:report_filter>', views.Transaction.create_report, name='api-create_report'),
]

gmovies_raffle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('transaction.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('accounts/', include('core.urls')),
    path('transaction/', include('transaction.urls')),
    path('user/', include('user.urls')),
    path('group/', include('group.urls')),
    path('permission/', include('permission.urls')),
    path('raffle/', include('raffle.urls')),
]

permission/urls.py
from django.urls import path
from . import views

app_name = 'permission'
urlpatterns = [
    path('list', views.List.as_view(), name='permission-list'),
    path('add', views.Add.as_view(), name='add'),
    path('edit/<int:permission_id>', views.Edit.as_view(), name='edit'),
    path('delete/<int:permission_id>', views.Delete.as_view(), name='delete'),
]

permission/models.py
from django.db import models

class UL(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.TextField()
    slug = models.TextField()

permission/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.views import generic, View
from django.utils import timezone
from .models import UL as Permission

class List(LoginRequiredMixin,View):
    template_name = 'permission/list.html'

    def get(self, request, *args, **kwargs):
        offset      = int(request.GET['offset']) if 'offset' in request.GET else 0
        limit       = int(request.GET['limit']) if 'limit' in request.GET else 10
        page        = int(request.GET['page']) if 'page' in request.GET else 1
        search      = str(request.GET['search']) if 'search' in request.GET else None

        items       = Permission.objects.all()
        paginator   = Paginator(items, limit)
        data_list   = paginator.get_page(page)

        data = {
                'items': data_list,
                'all_count': paginator.count,
                'current_count': len(data_list),
                'offset': offset,
                'limit': limit,
                'page': page
            }
        
        if search is not None:
            items = Permission.objects.all()

            if search != '':
                items = Permission.objects.filter(name__contains=search) | Permission.objects.filter(slug__contains=search)

            paginator   = Paginator(items, limit)
            data_list   = paginator.get_page(page)

            data = {
                'items': data_list,
                'all_count': paginator.count,
                'current_count': len(data_list),
                'offset': offset,
                'limit': limit,
                'page': page,
            }

        return render(request, self.template_name, data)

class Add(LoginRequiredMixin,View):
    errors          = []
    template_name   = 'permission/add.html'
    message         = ''

    def get(self, request):
        data = { 
            'message': self.message,
            'errors': self.errors
        }

        return render(request, self.template_name, data)

    def post(self, request):
        p_name = request.POST['name'] if request.POST['name'] != '' else None
        p_slug = request.POST['slug'] if request.POST['slug'] != '' else None

        self.errors = []

        if p_name is None:
            self.errors.append('Name Field is Required.')

        if p_slug is None:
            self.errors.append('Slug Field is Required.')

        if p_slug is not None:
            p = Permission.objects.filter(slug=p_slug)

            if len(p) != 0:
                self.errors.append('Slug Field must be unique.')
        
        if len(self.errors) == 0:
            self.message = 'Successfully Added.'
            Permission(name=p_name, slug=p_slug).save()

            data = {
                'message': self.message,
                'errors': self.errors
            }

            return JsonResponse(data)

        self.message = 'Fields are required.'

        data = {
            'message': self.message,
            'errors': self.errors
        }

        return JsonResponse(data)

class Edit(LoginRequiredMixin,View):
    template_name   = 'permission/edit.html'
    message         = ''
    errors          = []

    def get(self, request, permission_id):
        g       = Permission.objects.filter(id=permission_id)
        data    = {
            'items': g,
            'errors': self.errors,
            'message': self.message
        }

        return render(request, self.template_name, data)
    
    def post(self, request, permission_id):
        p_name = request.POST['name'] if request.POST['name'] != '' else None
        p_slug = request.POST['slug'] if request.POST['slug'] != '' else None

        g = Permission.objects.filter(id=permission_id)

        self.errors = []

        if p_name is None:
            self.errors.append('Name Field is Required.')

        if p_slug is None:
            self.errors.append('Slug Field is Required.')

        if p_slug is not None:
            if g[0].slug != p_slug:
                p = Permission.objects.filter(slug=p_slug)

                if len(p) != 0:
                    self.errors.append('Slug Field must be unique.')
        
        if len(self.errors) == 0:
            self.message = 'Successfully Added.'
            g.update(name=p_name, slug=p_slug)

            data    = {
                'errors': self.errors,
                'message': self.message
            }

            return JsonResponse(data)

        self.message = 'Fields are required.'

        data    = {
            'errors': self.errors,
            'message': self.message
        }

        return JsonResponse(data)

class Delete(LoginRequiredMixin,View):
    def get(self, request, permission_id):
        Permission.objects.filter(id=permission_id).delete()

        return HttpResponseRedirect('/permission/list?status=deleted')

permission/templates/permission/add.html
<div class="title">Add Permission</div>
<div class="errors"></div>
<form method="POST" action="{% url 'permission:add' %}" class="submit">
    {% csrf_token %}
    <div class="form-group label-floating">
        <label for="name" class="control-label">Name</label>
        <input id="name" type="text" class="form-control" name="name" placeholder="Enter name here" autofocus>
    </div>

    <div class="form-group label-floating">
        <label for="description" class="control-label">Slug</label>
        <input id="description" type="text" class="form-control" name="slug" placeholder="Enter slug here">
    </div>
    <div class="form-group">
        <button id="save" type="submit" class="btn btn-primary btn-sm">Save</button>
    </div>
</form>

{% block scrips %}
<script>
	$('.submit').on('submit', function(e){
		e.preventDefault();
		var dis = $(this)
		
		var form = new FormData(dis[0]);

		$.ajax({
			type: 'POST',
			url: dis.attr('action'),
			data: form,
			processData: false,
    	contentType: false,
			beforeSend: function(){
				$('#save').html('Saving ...').attr('disabled','disabled');
			},
			success: function(response){
				if(response.message == 'Fields are required.')
				{
					var er = '<div class="alert alert-danger">';
					er += '<p><b>'+response.message+'</b></p>';

					for(i = 0; i< response.errors.length;i++)
					{
						er += '<small>'+response.errors[i]+'</small><br>';
					}
					er += '</div><br><br>';

					$('.errors').html(er);
				}
				else location.href = "{% url 'permission:permission-list' %}?status=added";

				$('#save').html('Save').removeAttr('disabled');
			}
		});
	});
</script>
{% endblock %}

permission/templates/permission/edit.html
<div class="title">Edit Group</div>
<div class="errors"></div>
<form method="POST" action="{% url 'permission:edit' items.0.id %}" class="submit">
    {% csrf_token %}
    <div class="form-group label-floating">
        <label for="name" class="control-label">Name</label>
        <input id="name" type="text" class="form-control" name="name" value="{{ items.0.name }}" placeholder="Enter name here" autofocus>
    </div>

    <div class="form-group label-floating">
        <label for="description" class="control-label">Slug</label>
        <input id="description" type="text" class="form-control" name="slug" value="{{ items.0.slug }}" placeholder="Enter slug here">
    </div>
    </div>
    <div class="form-group">
        <button id="save" type="submit" class="btn btn-primary btn-sm">Update</button>
    </div>
</form>

{% block scrips %}
<script>
	$('.submit').on('submit', function(e){
		e.preventDefault();
		var dis = $(this)
		
		var form = new FormData(dis[0]);

		$.ajax({
			type: 'POST',
			url: dis.attr('action'),
			data: form,
			processData: false,
    	contentType: false,
			beforeSend: function(){
				$('#save').html('Saving ...').attr('disabled','disabled');
			},
			success: function(response){
				if(response.message == 'Fields are required.')
				{
					var er = '<div class="alert alert-danger">';
					er += '<p><b>'+response.message+'</b></p>';

					for(i = 0; i< response.errors.length;i++)
					{
						er += '<small>'+response.errors[i]+'</small><br>';
					}
					er += '</div><br><br>';

					$('.errors').html(er);
				}
				else location.href = "{% url 'permission:permission-list' %}?status=added";

				$('#save').html('Save').removeAttr('disabled');
			}
		});
	});
</script>
{% endblock %}

permission/templates/permission/list.html
{% extends "layout/base.html" %}
{% load staticfiles %}

{% block title %}Permissions | {{ settings.APP_NAME_TEXT }}{% endblock %}
{% block styles %}
<link rel='stylesheet' href='https://cdn.datatables.net/1.10.19/css/dataTables.foundation.min.css'>
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css'>
{% endblock %}

{% block content %}
<div class="content">
	<form method="GET" class="search-form">
		<div class="action">
			<input id="search" type="text" name="search" placeholder="Search..." value="{{request.GET.search}}">
			<span class="search-icon"><a href="#"><img class="search" src="{% static '/assets/img/icon/search-button.png' %}"></a></span>
			<a id="addPermission" class="btn btn-primary btn-sm uaction" data-action="add" data-target=".addPermission" data-url="{% url 'permission:add' %}">Add Permission</a>
		</div>
	</form>

	<div class="table-responsives">
		<table id="users" class="table table-bordered nowrap" style="width:100%">
			<thead>
				<tr>
					<th style="width: 50%">Name</th>
					<th style="width: 30%">Slug</th>
					<th style="width: 15%" class="text-center">Actions</th>
				</tr>
			</thead>
			<tbody>
				{% if items|len == 0 %}
				<tr>
					<td colspan="3"><b>No Data Found.</b></td>
				</tr>
				{% endif %}
				{% for a in items %}
				<tr>
					<td>{{ a.name }}</td>
					<td>{{ a.slug }}</td>
					<td class="text-center">
						<div class="actions">
							<img class="uaction" data-action="edit" data-target=".addPermission" data-url="{% url 'permission:edit' a.id %}" src="{% static '/assets/img/icon/ic-edit.png' %}" title="Edit">
							<img class="uaction" data-action="delete" data-target="#deleteModal" data-url="{% url 'permission:delete' a.id %}" src="{% static '/assets/img/icon/ic-delete.png' %}" title="Delete">
						</div>
					</td>
				</tr>
				{% endfor %}
			</tbody>                  
		</table>
	</div>
	<div class="paging">
		<div class="paging-inner-1">
			<div>Showing <span>{% if current_count != 0 %}1{% else %}0{% endif %}</span> to <span>{{current_count}}</span> of <span>{{all_count}}</span></div>
			<div class="dropdown">
				<select class="form-control per_page">
					{% for i in 100|toPerPage:20 %}
					<option value="{{ i }}" {% if i == limit %}selected="selected"{% endif %}>{{ i }}</option>
					{% endfor %}
				</select>
			</div>
			<div> per page</div>
		</div>

		<div class="paging-inner-2">
			<nav aria-label="...">
				<ul class="pagination">
					{% for n in items.paginator.page_range %}
						{% if items.number == n %}
							<li class="active">
								<a class="page-link">{{ n }}</a>
							</li>
						{% elif n > items.number|add:'-2' and n < items.number|add:'2' %}
							<li>
								<a class="page-link" href="{{ request.get_full_path }}&page={{ n }}">{{ n }}</a>
							</li>
						{% endif %}
					{% endfor %}
				</ul>
			</nav>
		</div>
	</div>
	<div id="overlay"></div>
	<!-- Right Navigation -->
	<div id="mySidepanel" class="sidepanel">
		<div>
			<a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
		</div>
		<div class="addPermission margin"><h2 class="text-center">Loading ...</h2></div>
	</div>
</div>

<!-- Delete Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-sm" role="document">
		<div class="modal-content modal-content-custom">
			<div class="modal-body">
				<div class="title">Delete Item</div>
				<div class="question">Are you sure you want to delete this data ?</div>
				<div class="actions">
				<button type="button" class="btn yes delete">Yes</button>
				<button type="button" class="btn no" data-dismiss="modal">No</button>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
<script type="text/javascript">
	$(document).ready(function(){
		$('[data-toggle="popover"]').popover({
		    html: true,
		    content: function() {
		        return $('#popover-content').html();
		    }
		});

		$('.per_page').change(function(){
			var dis = $(this)
		
			location.href = "{% if 'search' in request.get_full_path %}{{ request.get_full_path }}&{% else %}?{% endif %}limit="+dis.val();
		});

		$('.delete').click(function(){
			var dis = $(this)
			url = dis.data('url')
			location.href = url;
		});

		$('.uaction').on('click', function(){
			var dis = $(this)
			var url = dis.data('url');
			var action = dis.data('action');
			var target = dis.data('target');
			
			if(action == 'delete')
			{
				$('.delete').attr('data-url', url);
				$(target).modal('show');
			}
			else
			{
				$.get(url, function(page){
					openNav();
					$(target).html(page);
				});
			}
		});

		$('.search').click(function(){
			$('.search-form').submit();
		});
	});

	function openNav() 
	{
		document.getElementById("mySidepanel").style.width = "450px";
		document.getElementById("overlay").style.width = "100%";
		$('body').css("overflow", "hidden");
	}

	function closeNav() 
	{
		document.getElementById("mySidepanel").style.width = "0";
		document.getElementById("overlay").style.width = "0";
		$('body').css("overflow", "auto");
	}
</script>
{% endblock %}