api/urls.py
from django.urls import path
from . import views

app_name = 'api'
urlpatterns = [
    # update to cancel transaction entry
    path('v1/transaction/cancel/<str:transaction_id>', views.Transaction.cancel, name='api-cancel_transation'),
    path('v1/transaction/void/<str:transaction_id>', views.Transaction.void_transaction, name='api-void_transation'),
    path('v1/transaction/unvoid/<str:transaction_id>', views.Transaction.unvoid_transaction, name='api-unvoid_transation'),
    path('v1/transaction/report/<str:report_filter>', views.Transaction.create_report, name='api-create_report'),
]

gmovies_raffle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('transaction.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('accounts/', include('core.urls')),
    path('transaction/', include('transaction.urls')),
    path('user/', include('user.urls')),
    path('group/', include('group.urls')),
    path('permission/', include('permission.urls')),
    path('raffle/', include('raffle.urls')),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('list', views.List.as_view(), name='user-list'),
    path('add', views.Add.as_view(), name='add'),
    path('edit/<int:user_id>', views.Edit.as_view(), name='edit'),
    path('delete/<int:user_id>', views.Delete.as_view(), name='delete'),
    path('update-profile/<int:user_id>', views.UpdateProfile.as_view(), name='updateprofile'),
    path('change-password/<int:user_id>', views.ChangePassword.as_view(), name='changepassword'),
    path('change-password-from-profile/<int:user_id>', views.ChangePassword2.as_view(), name='changepassword2'),
    path('profile', views.Profile.as_view(), name='profile'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import User

class UserInfo(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    mobile = models.CharField(max_length=30, null=True)
    avatar = models.TextField(null=True)

user/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
from django.views import generic, View
from django.utils import timezone
from django.contrib.auth.models import User
from group.models import UL as Group
from .models import UserInfo
from group.models import User as UserGroups
from validate_email import validate_email

class List(LoginRequiredMixin,View):
    template_name   = 'user/list.html'

    def get(self, request, *args, **kwargs):
        offset      = int(request.GET['offset']) if 'offset' in request.GET else 0
        limit       = int(request.GET['limit']) if 'limit' in request.GET else 10
        page        = int(request.GET['page']) if 'page' in request.GET else 1
        search      = str(request.GET['search']) if 'search' in request.GET else None

        items       = User.objects.filter(is_superuser=False)
        paginator   = Paginator(items, limit)
        data_list   = paginator.get_page(page)

        data = {
            'items': data_list,
            'all_count': paginator.count,
            'current_count': len(data_list),
            'offset': offset,
            'limit': limit,
            'page': page,
        }

        if search is not None:
            items = User.objects.filter(is_superuser=False)

            if search != '':
                items = User.objects.filter(first_name__contains=search) | User.objects.filter(last_name__contains=search) | User.objects.filter(email__contains=search) | User.objects.filter(userinfo__mobile__contains=search)

            paginator   = Paginator(items, limit)
            data_list   = paginator.get_page(page)

            data = {
                'items': data_list,
                'all_count': paginator.count,
                'current_count': len(data_list),
                'offset': offset,
                'limit': limit,
                'page': page,
            }

        return render(request, self.template_name, data)

class Add(LoginRequiredMixin,View):
    errors          = []
    template_name   = 'user/add.html'
    message         = ''

    def get(self, request):
        data = {
            'groups': Group.objects.all(),
            'message': self.message,
            'errors': self.errors
        }

        return render(request, self.template_name, data)
    
    def post(self, request):
        u_first_name    = request.POST['first_name'] if request.POST['first_name'] != '' else None
        u_last_name     = request.POST['last_name'] if request.POST['last_name'] != '' else None
        u_email         = request.POST['email'] if request.POST['email'] != '' else None
        u_mobile        = request.POST['mobile'] if request.POST['mobile'] != '' else None
        u_group         = request.POST['group'] if request.POST['group'] != '' else None
        u_is_active     = True if 'is_active' in request.POST and request.POST['is_active'] == '1' else False

        self.errors = []

        if u_first_name is None:
            self.errors.append('First Name Field is Required.')
        
        if u_last_name is None:
            self.errors.append('Last Name Field is Required.')

        if u_email is None:
            
            self.errors.append('Email Field is Required.')

        if u_email is not None:
            is_valid = validate_email(u_email)

            if not is_valid:
                self.errors.append('Invalid Email Address.')

            check = User.objects.filter(email=u_email)
            if len(check) != 0 and str(check[0].email) == str(u_email):
                self.errors.append('Email Address Already Taken.')

        if u_mobile is None:
            self.errors.append('Mobile Field is Required.')

        if u_group is None:
            self.errors.append('Group Field is Required.')
        
        if len(self.errors) == 0:
            self.message = 'Successfully Added.'
            u = User(first_name=u_first_name, last_name=u_last_name, username=u_email ,email=u_email, is_active=u_is_active)
            u.save()

            UserInfo(mobile=u_mobile, user_id=u.id).save()
            UserGroups(user_id=u.id, group_id=int(u_group)).save()

            data = {
                'message': self.message,
                'errors': self.errors
            }

            return JsonResponse(data)

        self.message = 'Fields are required.'

        data = {
            'message': self.message,
            'errors': self.errors
        }

        return JsonResponse(data)
    
class Edit(LoginRequiredMixin,View):
    errors          = []
    template_name   = 'user/edit.html'
    message         = ''

    def get(self, request, user_id):
        u = User.objects.filter(id=user_id)
        data = {
            'items': u,
            'groups': Group.objects.all(),
            'message': self.message,
            'errors': self.errors
        }

        return render(request, self.template_name, data)
    
    def post(self, request, user_id):
        u_first_name    = request.POST['first_name'] if request.POST['first_name'] != '' else None
        u_last_name     = request.POST['last_name'] if request.POST['last_name'] != '' else None
        u_email         = request.POST['email'] if request.POST['email'] != '' else None
        u_mobile        = request.POST['mobile'] if request.POST['mobile'] != '' else None
        u_group         = request.POST['group'] if request.POST['group'] != '' else None
        u_is_active     = True if 'is_active' in request.POST and request.POST['is_active'] == '1' else False

        g = User.objects.filter(id=user_id)

        self.errors = []

        if u_first_name is None:
            self.errors.append('First Name Field is Required.')
        
        if u_last_name is None:
            self.errors.append('Last Name Field is Required.')

        if u_email is None:
            self.errors.append('Email Field is Required.')

        if u_email is not None:
            is_valid = validate_email(u_email)

            if not is_valid:
                self.errors.append('Invalid Email Address.')
            
            check = User.objects.filter(email=u_email)
            
            if str(g[0].email) != (u_email):
                if len(check) != 0 and str(check[0].email) == str(u_email):
                    self.errors.append('Email Address Already Taken.')

        if u_mobile is None:
            self.errors.append('Mobile Field is Required.')

        if u_group is None:
            self.errors.append('Group Field is Required.')
        
        if len(self.errors) == 0:
            self.message = 'Successfully Updated.'
            u = User.objects.filter(id=user_id)
            u.update(first_name=u_first_name, last_name=u_last_name, username=u_email ,email=u_email, is_active=u_is_active)

            m = UserInfo.objects.filter(user_id=user_id)
            m.update(mobile=u_mobile)

            ug = UserGroups.objects.filter(user_id=user_id)
            ug.update(group_id=int(u_group))

            data = {
                'message': self.message,
                'errors': self.errors
            }

            return JsonResponse(data)

        self.message = 'Fields are required.'

        data = {
            'message': self.message,
            'errors': self.errors
        }

        return JsonResponse(data)

class ChangePassword(LoginRequiredMixin,View):
    errors          = []
    template_name   = 'user/password.html'
    message         = ''

    def get(self, request, user_id):
        u = User.objects.filter(id=user_id)
        data = {
            'items': u,
            'message': self.message,
            'errors': self.errors
        }

        return render(request, self.template_name, data)

    def post(self, request, user_id):
        password1 = str(request.POST['password']) if request.POST['password'] else None
        password2 = str(request.POST['password2']) if request.POST['password2'] else None

        u = User.objects.get(id=user_id)

        self.errors = []

        if password1 is None:
            self.errors.append('Password Field is required.')

        if password2 is None:
            self.errors.append('Confirm Password Field is required.')

        if password1 is not None or password2 is not None:
            if password1 != password2:
                self.errors.append('Password dont match.')
            
            else:
                u.set_password(password1)
                u.save()

                data = {
                    'message': self.message,
                    'errors': self.errors
                }

                return JsonResponse(data)
        
        self.message = 'Fields are required.'

        data = {
            'message': self.message,
            'errors': self.errors
        }

        return JsonResponse(data)

class UpdateProfile(LoginRequiredMixin, View):
    errors          = []
    message         = ''

    def post(self, request, user_id):
        u_first_name    = request.POST['first_name'] if request.POST['first_name'] != '' else None
        u_last_name     = request.POST['last_name'] if request.POST['last_name'] != '' else None
        u_email         = request.POST['email'] if request.POST['email'] != '' else None
        u_mobile        = request.POST['mobile'] if request.POST['mobile'] != '' else None

        g = User.objects.filter(id=user_id)

        self.errors = []

        if u_first_name is None:
            self.errors.append('First Name Field is Required.')
        
        if u_last_name is None:
            self.errors.append('Last Name Field is Required.')

        if u_email is None:
            self.errors.append('Email Field is Required.')

        if u_email is not None:
            is_valid = validate_email(u_email)

            if not is_valid:

user/templates/user/add.html
<div class="title">Add User</div>
<div class="errors"></div>
<form method="POST" action="{% url 'user:add' %}" class="submit">
	{% csrf_token %}
	<div class="form-group label-floating">
		<label for="fullname" class="control-label">First Name</label>
		<input id="fullname" type="text" class="form-control" name="first_name" placeholder="Enter your first name" autofocus>
	</div>

	<div class="form-group label-floating">
		<label for="fullname" class="control-label">Last Name</label>
		<input id="fullname" type="text" class="form-control" name="last_name" placeholder="Enter your last name" autofocus>
	</div>

	<div class="form-group label-floating">
		<label for="email" class="control-label">Email</label>
		<input id="email" type="text" class="form-control" name="email" placeholder="sample@email.com">
	</div>

	<div class="form-group label-floating">
		<label for="password" class="control-label">Mobile</label>
		<div class="mobile">
			<div class="input-group-prepend">
				<span class="input-group-text">+63</span>
			</div>
			<input id="mobile-number" type="text" class="form-control" name="mobile" placeholder="917xxxxxxx">
		</div>
	</div>

	<div class="form-group label-floating">
		<label for="password" class="control-label">Groups</label>
		<select class="form-control" id="groups" name="group">
			<option value="">Choose</option>
			{% for g in groups %}
			<option value="{{g.id}}">{{ g.name }}</option>
			{% endfor %}
		</select>
	</div>

	<div class="form-group label-floating activate">
		<div class="activate-inner">
			<label class="control-label">Activate account</label>
			<div class="switch">
				<label>
					<input type="checkbox" class="form-control" name="is_active" value="1">
					<span class="lever"></span>
				</label>
			</div>
		</div>
	</div>

	<div class="form-group">
		<button id="save" type="submit" class="btn btn-primary btn-sm">Save</button>
	</div>
</form>

{% block scrips %}
<script>
	$('.submit').on('submit', function(e){
		e.preventDefault();
		var dis = $(this)
		
		var form = new FormData(dis[0]);

		$.ajax({
			type: 'POST',
			url: dis.attr('action'),
			data: form,
			processData: false,
    	contentType: false,
			beforeSend: function(){
				$('#save').html('Saving ...').attr('disabled','disabled');
			},
			success: function(response){
				if(response.message == 'Fields are required.')
				{
					var er = '<div class="alert alert-danger">';
					er += '<p><b>'+response.message+'</b></p>';

					for(i = 0; i< response.errors.length;i++)
					{
						er += '<small>'+response.errors[i]+'</small><br>';
					}
					er += '</div><br><br>';

					$('.errors').html(er);
				}
				else location.href = "{% url 'user:user-list' %}?status=added";

				$('#save').html('Save').removeAttr('disabled');
			}
		});
	});
</script>
{% endblock %}

user/templates/user/edit.html
<div class="title">Update User Info</div>
<div class="errors"></div>
<form method="POST" action="{% url 'user:edit' items.0.id %}" class="submit">
	{% csrf_token %}
	<div class="form-group label-floating">
		<label for="fullname" class="control-label">First Name</label>
		<input id="fullname" type="text" value="{{ items.0.first_name}}" class="form-control" name="first_name" placeholder="Enter your first name" autofocus>
	</div>

	<div class="form-group label-floating">
		<label for="fullname" class="control-label">Last Name</label>
		<input id="fullname" type="text" value="{{ items.0.last_name}}" class="form-control" name="last_name" placeholder="Enter your last name" autofocus>
	</div>

	<div class="form-group label-floating">
		<label for="email" class="control-label">Email</label>
		<input id="email" type="text" class="form-control" value="{{ items.0.email}}" name="email" placeholder="sample@email.com">
	</div>

	<div class="form-group label-floating">
		<label for="password" class="control-label">Mobile</label>
		<div class="mobile">
			<div class="input-group-prepend">
				<span class="input-group-text">+63</span>
			</div>
			<input id="mobile-number" type="text" value="{{ items.0.userinfo.mobile}}" class="form-control" name="mobile" placeholder="917xxxxxxx">
		</div>
	</div>

	<div class="form-group label-floating">
		<label for="password" class="control-label">Groups</label>
		<select class="form-control" id="groups" name="group">
			<option value="">Choose</option>
			{% for g in groups %}
			<option value="{{g.id}}" {% if g.id|toStr == items.0.user.group.id|toStr %}selected="selected"{% endif %}>{{g.name}}</option>
			{% endfor %}
		</select>
	</div>

	<div class="form-group label-floating activate">
		<div class="activate-inner">
			<label class="control-label">Activate account</label>
			<div class="switch">
				<label>
					<input type="checkbox" {% if items.0.is_active %}checked="checked"{% endif %}  class="form-control" name="is_active" value="1">
					<span class="lever"></span>
				</label>
			</div>
		</div>
	</div>

	<div class="form-group">
		<button id="save" type="submit" class="btn btn-primary btn-sm">Update</button>
	</div>
</form>

{% block scrips %}
<script>
	$('.submit').on('submit', function(e){
		e.preventDefault();
		var dis = $(this)
		
		var form = new FormData(dis[0]);

		$.ajax({
			type: 'POST',
			url: dis.attr('action'),
			data: form,
			processData: false,
    	contentType: false,
			beforeSend: function(){
				$('#save').html('Saving ...').attr('disabled','disabled');
			},
			success: function(response){
				if(response.message == 'Fields are required.')
				{
					var er = '<div class="alert alert-danger">';
					er += '<p><b>'+response.message+'</b></p>';

					for(i = 0; i< response.errors.length;i++)
					{
						er += '<small>'+response.errors[i]+'</small><br>';
					}
					er += '</div><br><br>';

					$('.errors').html(er);
				}
				else location.href = "{% url 'user:user-list' %}?status=updated";

				$('#save').html('Save').removeAttr('disabled');
			}
		});
	});
</script>
{% endblock %}

user/templates/user/list.html
{% extends "layout/base.html" %}
{% load staticfiles %}

{% block title %}Users | {{ settings.APP_NAME_TEXT }}{% endblock %}
{% block styles %}
<link rel='stylesheet' href='https://cdn.datatables.net/1.10.19/css/dataTables.foundation.min.css'>
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css'>
{% endblock %}

{% block content %}
<div class="content">
	<form method="GET" class="search-form">
		<div class="action">
			<input id="search" type="text" name="search" placeholder="Search..." value="{{request.GET.search}}">
			<span class="search-icon"><a href="#"><img class="search" src="{% static '/assets/img/icon/search-button.png' %}"></a></span>
			<a id="addUser" class="btn btn-primary btn-sm uaction" data-action="add" data-target=".addUser" data-url="{% url 'user:add' %}">Add User</a>
		</div>
	</form>

	<div class="table-responsives">
		<table id="users" class="table table-bordered nowrap" style="width:100%">
			<thead>
				<tr>
					<th style="width: 20%">Name</th>
					<th style="width: 20%">Email Address</th>
					<th style="width: 15%">Mobile</th>
					<th style="width: 15%">Group</th>
					<th style="width: 15%">Status</th>
					<th style="width: 12%" class="text-center">Actions</th>
				</tr>
			</thead>
			<tbody>
				{% if items|len == 0 %}
				<tr>
					<td colspan="6"><b>No Data Found.</b></td>
				</tr>
				{% endif %}
				{% for item in items %}
				<tr>
					<td>{{item.first_name}} {{item.last_name}}</td>
					<td>{{item.email}}</td>
					<td>{{item.userinfo.mobile}}</td>
					<td>{{item.user.group.name}}</td>
					<td>
						{% if item.is_active %}
						<div  class="users-green">Active</div>
						{% else %}
						<div  class="users-gray">Inactive</div>
						{% endif %}
					</td>
					<td class="text-center">
						<div class="actions">
							<img class="uaction" data-action="edit" data-target=".addUser" data-url="{% url 'user:edit' item.id %}" src="{% static '/assets/img/icon/ic-edit.png' %}" title="Edit">
							<img class="uaction" data-action="delete" data-target="#deleteModal" data-url="{% url 'user:delete' item.id %}" src="{% static '/assets/img/icon/ic-delete.png' %}" title="Delete">
							<img class="uaction" data-action="changepassword" data-target=".addUser" data-url="{% url 'user:changepassword' item.id %}" src="{% static '/assets/img/icon/ic-resetpassword.png' %}" title="Reset Password">
						</div>
					</td>
				</tr>
				{% endfor %}	                
			</tbody>                  
		</table>
	</div>
	<div class="paging">
		<div class="paging-inner-1">
			<div>Showing <span>{% if current_count != 0 %}1{% else %}0{% endif %}</span> to <span>{{current_count}}</span> of <span>{{all_count}}</span></div>
			<div class="dropdown">
				<select class="form-control per_page">
					{% for i in 100|toPerPage:20 %}
					<option value="{{ i }}" {% if i == limit %}selected="selected"{% endif %}>{{ i }}</option>
					{% endfor %}
				</select>
			</div>
			<div> per page</div>
		</div>

		<div class="paging-inner-2">
			<nav aria-label="...">
				<ul class="pagination">
					{% for n in items.paginator.page_range %}
						{% if items.number == n %}
							<li class="active">
								<a class="page-link">{{ n }}</a>
							</li>
						{% elif n > items.number|add:'-2' and n < items.number|add:'2' %}
							<li>
								<a class="page-link" href="{{ request.get_full_path }}&page={{ n }}">{{ n }}</a>
							</li>
						{% endif %}
					{% endfor %}
				</ul>
			</nav>
		</div>
	</div>
	<div id="overlay"></div>
	<!-- Right Navigation -->
	<div id="mySidepanel" class="sidepanel">
		<div>
			<a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
		</div>
		<div class="addUser margin"><h2 class="text-center">Loading ...</h2></div>
	</div>
</div>

<!-- Delete Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-sm" role="document">
		<div class="modal-content modal-content-custom">
			<div class="modal-body">
				<div class="title">Delete Item</div>
				<div class="question">Are you sure you want to delete this data ?</div>
				<div class="actions">
				<button type="button" class="btn yes delete">Yes</button>
				<button type="button" class="btn no" data-dismiss="modal">No</button>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
<script type="text/javascript">

	$(document).ready(function(){
		$('[data-toggle="popover"]').popover({
		    html: true,
		    content: function() {
		        return $('#popover-content').html();
		    }
		});

		$('.per_page').change(function(){
			var dis = $(this)
		
			location.href = "{% if 'search' in request.get_full_path %}{{ request.get_full_path }}&{% else %}?{% endif %}limit="+dis.val();
		});

		$('.delete').click(function(){
			var dis = $(this)
			url = dis.data('url')
			location.href = url;
		});

		$('.uaction').on('click', function(){
			var dis = $(this)
			var url = dis.data('url');
			var action = dis.data('action');
			var target = dis.data('target');
			
			if(action == 'delete')
			{
				$('.delete').attr('data-url', url);
				$(target).modal('show');
			}
			else
			{
				$.get(url, function(page){
					openNav();
					$(target).html(page);
				});
			}
		});

		$('.search').click(function(){
			$('.search-form').submit();
		});
	});

	function openNav() 
	{
		document.getElementById("mySidepanel").style.width = "450px";
		document.getElementById("overlay").style.width = "100%";
		$('body').css("overflow", "hidden");
	}

	function closeNav() 
	{
		document.getElementById("mySidepanel").style.width = "0";
		document.getElementById("overlay").style.width = "0";
		$('body').css("overflow", "auto");
	}
</script>
{% endblock %}

user/templates/user/password.html
<div class="title">Update Password</div>
<div class="errors"></div>
<form method="POST" action="{% url 'user:changepassword' items.0.id %}" class="submit">
	{% csrf_token %}
	<div class="form-group label-floating">
		<label for="fullname" class="control-label">Password</label>
		<input id="fullname" type="password" class="form-control" name="password" placeholder="Enter Password" autofocus>
	</div>

	<div class="form-group label-floating">
		<label for="fullname" class="control-label">Repeat Password</label>
		<input id="fullname" type="password" class="form-control" name="password2" placeholder="Repeat Password">
	</div>

	<div class="form-group label-floating">
		<button id="save" type="submit" class="btn btn-primary">Update</button>
	</div>
</form>

{% block scrips %}
<script>
	$('.submit').on('submit', function(e){
		e.preventDefault();
		var dis = $(this)
		
		var form = new FormData(dis[0]);

		$.ajax({
			type: 'POST',
			url: dis.attr('action'),
			data: form,
			processData: false,
		contentType: false,
			beforeSend: function(){
				$('#save').html('Updating ...').attr('disabled','disabled');
			},
			success: function(response){
				if(response.message == 'Fields are required.')
				{
					var er = '<div class="alert alert-danger">';
					er += '<p><b>'+response.message+'</b></p>';

					for(i = 0; i< response.errors.length;i++)
					{
						er += '<small>'+response.errors[i]+'</small><br>';
					}
					er += '</div><br><br>';

					$('.errors').html(er);
				}
				else location.href = "{% url 'user:user-list' %}?status=updated";

				$('#save').html('Update Password').removeAttr('disabled');
			}
		});
	});
</script>
{% endblock %}

user/templates/user/profile.html
{% extends "layout/base.html" %}
{% load staticfiles %}

{% block title %}Profile | {{ settings.APP_NAME_TEXT }}{% endblock %}

{% block content %}
<div class="content">
    <form method="POST" action="{% url 'user:updateprofile' items.0.id %}" class="submit-profile">
        {% csrf_token %}
        <div class="container" style="height: auto">
            <div class="info">
            </div>
            <div class="info">
                <div class="errors"></div>
                <div class="form-group label-floating">
                    <label for="fullname" class="control-label">First Name</label>
                    <input type="text" class="form-control" name="first_name" value="{{request.user.first_name}}" placeholder="Enter your first name" autofocus>
                </div>

                <div class="form-group label-floating">
                    <label for="fullname" class="control-label">Last Name</label>
                    <input type="text" class="form-control" name="last_name" value="{{request.user.last_name}}" placeholder="Enter your last name" autofocus>
                </div>

                <div class="form-group label-floating">
                    <label for="email" class="control-label">Email</label>
                    <input id="email" type="text" class="form-control" name="email"" value="{{request.user.email}}" placeholder="sample@email.com">
                </div>

                <div class="form-group label-floating">
                    <label for="password" class="control-label">Mobile</label>
                    <div class="mobile">
                        <div class="input-group-prepend">
                            <span class="input-group-text">+63</span>
                        </div>
                        <input id="mobile-number" type="text" class="form-control"value="{{request.user.userinfo.mobile}}" name="mobile" placeholder="917xxxxxxx">
                    </div>
                </div>	

                <div class="form-group label-floating">
                    <label for="password" class="control-label">Password</label>
                    <div class="change-pw"><a href="#" class="changepassword" data-target=".changePassword" data-url="{% url 'user:changepassword2' request.user.id %}">Change Password</a></div>
                </div>

                <div class="form-group">
                    <button id="save" type="submit" class="btn btn-primary btn-sm">Save changes</button>
                </div>			
            </div>
        </div>
    </form>

    <div id="overlay"></div>
	<!-- Right Navigation -->
	<div id="mySidepanel" class="sidepanel">
		<div>
			<a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
		</div>
		<div class="changePassword margin"><h2 class="text-center">Loading ...</h2></div>
	</div>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
    $(document).ready(function(){
        $('.changepassword').click(function(){
            var dis = $(this)
			var url = dis.data('url');
			var action = dis.data('action');
			var target = dis.data('target');
			
            $.get(url, function(page){
                openNav();
                $(target).html(page);
            });
        });

        $('.submit-profile').on('submit', function(e){
            e.preventDefault();
            var dis = $(this)
            
            var form = new FormData(dis[0]);

            $.ajax({
                type: 'POST',
                url: dis.attr('action'),
                data: form,
                processData: false,
            contentType: false,
                beforeSend: function(){
                    $('#save').html('Saving ...').attr('disabled','disabled');
                },
                success: function(response){
                    if(response.message == 'Fields are required.')
                    {
                        var er = '<div class="alert alert-danger">';
                        er += '<p><b>'+response.message+'</b></p>';

                        for(i = 0; i< response.errors.length;i++)
                        {
                            er += '<small>'+response.errors[i]+'</small><br>';
                        }
                        er += '</div><br><br>';

                        $('.errors').html(er);
                    }
                    else location.href = "/user/profile{{requestuser.id}}?status=updated";

                    $('#save').html('Update Password').removeAttr('disabled');
                }
            });
        });
    });

    function openNav() 
	{
		document.getElementById("mySidepanel").style.width = "450px";
		document.getElementById("overlay").style.width = "100%";
		$('body').css("overflow", "hidden");
	}

	function closeNav() 
	{
		document.getElementById("mySidepanel").style.width = "0";
		document.getElementById("overlay").style.width = "0";
		$('body').css("overflow", "auto");
	}
</script>
{% endblock %}