api/urls.py
from django.urls import path
from . import views

app_name = 'api'
urlpatterns = [
    # update to cancel transaction entry
    path('v1/transaction/cancel/<str:transaction_id>', views.Transaction.cancel, name='api-cancel_transation'),
    path('v1/transaction/void/<str:transaction_id>', views.Transaction.void_transaction, name='api-void_transation'),
    path('v1/transaction/unvoid/<str:transaction_id>', views.Transaction.unvoid_transaction, name='api-unvoid_transation'),
    path('v1/transaction/report/<str:report_filter>', views.Transaction.create_report, name='api-create_report'),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
	path('login/', views.Login.as_view(), name='login'),
	path('signoff/', views.logout_view, name='logout'),
	path('signup/', views.Signup.as_view(), name='signup'),
	path('success_signup/', views.SuccessSignup.as_view(), name='success_signup'),
	path('activate/<uidb64>/<token>/', views.activate, name='activate_email'),
    path('password/reset/', views.ResetPassword.as_view(), name='password_reset'),
    path('password/change/<token>/', views.ChangePassword.as_view(), name='password_change'),
]

gmovies_raffle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('transaction.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('accounts/', include('core.urls')),
    path('transaction/', include('transaction.urls')),
    path('user/', include('user.urls')),
    path('group/', include('group.urls')),
    path('permission/', include('permission.urls')),
    path('raffle/', include('raffle.urls')),
]

group/urls.py
from django.urls import path
from . import views

app_name = 'group'
urlpatterns = [
    path('list', views.List.as_view(), name='group-list'),
    path('add', views.Add.as_view(), name='add'),
    path('edit/<int:group_id>', views.Edit.as_view(), name='edit'),
    path('delete/<int:group_id>', views.Delete.as_view(), name='delete'),
]

permission/urls.py
from django.urls import path
from . import views

app_name = 'permission'
urlpatterns = [
    path('list', views.List.as_view(), name='permission-list'),
    path('add', views.Add.as_view(), name='add'),
    path('edit/<int:permission_id>', views.Edit.as_view(), name='edit'),
    path('delete/<int:permission_id>', views.Delete.as_view(), name='delete'),
]

transaction/urls.py
from django.urls import path
from . import views

app_name = 'transaction'
urlpatterns = [
    path('', views.List.as_view(), name='transaction'),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('list', views.List.as_view(), name='user-list'),
    path('add', views.Add.as_view(), name='add'),
    path('edit/<int:user_id>', views.Edit.as_view(), name='edit'),
    path('delete/<int:user_id>', views.Delete.as_view(), name='delete'),
    path('update-profile/<int:user_id>', views.UpdateProfile.as_view(), name='updateprofile'),
    path('change-password/<int:user_id>', views.ChangePassword.as_view(), name='changepassword'),
    path('change-password-from-profile/<int:user_id>', views.ChangePassword2.as_view(), name='changepassword2'),
    path('profile', views.Profile.as_view(), name='profile'),
]

core/models.py
import datetime
from django.db import models
from django.utils import timezone

class PasswordResets(models.Model):
	email = models.CharField(max_length=255)
	token = models.CharField(max_length=255)
	created_at 	= models.DateTimeField(timezone.now())

core/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.core.validators import validate_email
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.CharField(max_length=100, required=True)
    password = forms.CharField(widget=forms.PasswordInput, max_length=100, required=True)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)

            if not user or not user.is_active:
                raise forms.ValidationError("Sorry, Invalid Email/Username or password. Please try again.")

        return self.cleaned_data

class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class PasswordResetForm(forms.Form):
    email = forms.EmailField(max_length=100, required=True)

    def clean(self):
        email = self.cleaned_data.get('email')

        if email and not User.objects.filter(email=email).exists():
            raise forms.ValidationError("We could'nt find that email address, Please try again.")

        return self.cleaned_data

class ChangePasswordForm(forms.Form):
    email = forms.EmailField(max_length=100, required=True, help_text='Required. Inform a valid and existing email address.')
    password = forms.CharField(widget=forms.PasswordInput, max_length=100, required=True)
    confirm_password = forms.CharField(widget=forms.PasswordInput, max_length=100, required=True)

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')

        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError("We could'nt find that email address, Please try again!")
            
        if password != confirm_password:
            raise forms.ValidationError("Password not match. Please try again!")

        return self.cleaned_data

core/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect, Http404, JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views import View
from django.utils import timezone
#from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth.models import User
from .forms import *
from .models import *
from .core_helpers import *

#class handing for account login
class Login(View):
    template_name='core/login.html'

    def get(self, request, *args, **kwargs):
        form  = LoginForm()

        if request.user.is_authenticated:
            return redirect('/')

        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('/')

        form = LoginForm(request.POST or None)
        username = request.POST['username']
        password = request.POST['password']
        next_uri = request.POST['next']

        if form.is_valid():
            user = authenticate(request, username=username, password=password)

            if user is None:
                user = authenticate(request, email=username, password=password)

            if user is not None:
                login(request, user)

                if not next_uri:
                    next_uri = '/'
                    
                return HttpResponseRedirect(str(next_uri))

        return render(request, self.template_name, {'form': form})

#class handing for account signup
class Signup(View):
    template_name = 'core/signup.html'

    def get(self, request, *args, **kwargs):
        form = SignupForm()

        if request.user.is_authenticated:
            return redirect('/')

        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('/')

        form = SignupForm(request.POST or None)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            send_email(request, user, {}, 'Account activation email.', 'core/mail/account_activation.html')
            messages.success(request, 'Successfully registered, Please check activation link on your email.')

            return redirect('/accounts/success_signup/?email='+user.email)

        return render(request, self.template_name, {'form': form})

#class handling for successfull signup
class SuccessSignup(View):
    template_name = 'core/success_signup.html'
    
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('/')

        email = request.GET['email']
        get_object_or_404(User, email=email)
        user =  User.objects.get(email=email)

        if user.is_active:
            raise Http404

        return render(request, self.template_name, {'email': email})

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('/')

        email = request.POST['email']
        get_object_or_404(User, email=email)
        user =  User.objects.get(email=email)

        if user.is_active:
            raise Http404

        user = User.objects.get(email=email)
        send_email(request, user, {},'Account activation email.', 'core/mail/account_activation.html')
        messages.success(request, "Activation link successfully sent to your email "+email)

        return render(request, self.template_name, {'email': email})

#class handling for resetting password
class ResetPassword(View):
    template_name = 'core/password/reset_password.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('/')
            
        form = PasswordResetForm()

        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('/')

        form = PasswordResetForm(request.POST or None)
        email = request.POST['email']

        if form.is_valid():
            if User.objects.filter(email=email).exists():
                user = User.objects.get(email=email)
                token = generate_token.make_token(User.objects.get(email=email))
                email = email
                created_at = timezone.now()

                if PasswordResets.objects.filter(email=email).exists():
                    pr = PasswordResets.objects.get(email=email)
                    pr.email = email
                    pr.token = token
                    pr.created_at = created_at
                    pr.save()
                    
                else:
                    pr = PasswordResets(email=email, token=token, created_at=created_at)
                    pr.save()

                messages.info(request, "Password reset link has been sent to your email.")
                data = {'token': token }
                send_email(request, user, {'token': token,},'Password reset link.', 'core/mail/password_reset.html')

        return render(request, self.template_name, {'form': form})

#class handling for resetting password
class ChangePassword(View):
    template_name = 'core/password/change_password.html'

    def get(self, request, token, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('/')

        form = ChangePasswordForm()
        get_object_or_404(PasswordResets, token=token)

        return render(request, self.template_name, {'form': form})

    def post(self, request, token, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('/')

        form = ChangePasswordForm(request.POST or None)
        email = request.POST['email']
        get_object_or_404(PasswordResets, token=token)

        if form.is_valid():
            user = User.objects.get(email=email)
            user.set_password(request.POST['password'])
            user.save()

            PasswordResets.objects.get(token=token).delete()
            messages.success(request, "You've successfully updated your password. You may now login with your new password!")

            return HttpResponseRedirect('/accounts/login/')

        return render(request, self.template_name, {'form': form})

#method for account activation via email link
def activate(request, uidb64, token):
    if request.user.is_authenticated:
            return redirect('/')

    try:
        uid = force_text(urlsafe_base64_decode(uidb64).decode())
        user = User.objects.get(pk=uid)

        if user.is_active:
            raise Http404
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and generate_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        messages.success(request, "You've Successfully activated your account.")

        return redirect('/')
    else:
        return render(request, 'account_activation_invalid.html')

#method for logout
@login_required
def logout_view(request):
    logout(request)

    return HttpResponseRedirect('/accounts/login')

core/templates/layout/includes/footer.html
<!-- begin scroll to top btn -->
<a href="javascript:;" class="btn btn-icon btn-circle btn-success btn-scroll-to-top fade" data-click="scroll-top"><i class="fa fa-angle-up"></i></a>
<!-- end scroll to top btn -->

core/templates/layout/includes/header.html
{% load staticfiles %}
<div class="header">
	{% if 'profile' in request.get_full_path %}
	<div class="left-header2">
		<div class="user"><span class="dot">{% if user.is_superuser %} {{request.user.username|firstUpper}} {% else %} {{request.user.first_name|firstUpper}} {% endif %}</span></div>
		<div class="user-label">My Profile</div>
	</div>
	<div class="right-header2">
		<div class="log-out"><a href="{% url 'core:logout' %}" class="log-out-inner">Log out</a></div>
	</div>
	{% else %}
	<div class="left-header">
		{% if request.resolver_match.url_name == 'transaction' %}
		<div class="transaction"><img src="{% static '/assets/img/icon/ic-transaction-report-blue.png' %}"></div>
		<div class="transaction-label">List of Transaction</div>
		{% endif %}

		{% if 'group' in request.get_full_path or 'user' in request.get_full_path or 'permission' in request.get_full_path  %}
		<div class="user"><img src="{% static '/assets/img/icon/ic-usermgmt-blue.png' %}"></div>
		<div class="user-label">User Management</div>
		<div class="menu-user">
			<ul>
				{% if 'user' in request.user.id|getPermissions|toStrArr or request.user.is_superuser %}
				<li class="menu-outer1"><a href="{% url 'user:user-list' %}"><div class="menu-inner1 hover1 {% if 'user' in request.get_full_path %} active {% endif %}">Users</div></a></li>
				{% endif %}
				
				{% if 'permission' in request.user.id|getPermissions|toStrArr or request.user.is_superuser %}
				<li class="menu-outer2"><a href="{% url 'permission:permission-list' %}"><div class="menu-inner2 hover2 {% if 'permission' in request.get_full_path %} active {% endif %}">Permissions</div></a></li>
				{% endif %}

				{% if 'group' in request.user.id|getPermissions|toStrArr or request.user.is_superuser %}
				<li class="menu-outer3"><a href="{% url 'group:group-list' %}"><div class="menu-inner3 hover1 {% if 'group' in request.get_full_path %} active {% endif %}">Groups</div></a></li>
				{% endif %}
			</ul>				
		</div>
		{% endif %}
	</div>
	<div class="right-header">
		<div class="user-profile">
			<span class="dot">{% if user.is_superuser %} {{request.user.username|firstUpper}} {% else %} {{request.user.first_name|firstUpper}} {% endif %}</span>
		</div>
		<div class="user-name">Hi, <a href="#" data-toggle="popover" data-placement="bottom"><span>{% if user.is_superuser %} {{request.user.username}} {% else %} {{request.user.first_name}} {% endif %}</span><i class='fa fa-angle-down'></i></a></div>
	</div>
	<!-- loaded popover content -->
	<ul id="popover-content" class="list-group" style="display: none">
		<div class="popover-inner"><a class="btn" href="{% url 'user:profile' %}" class="list-group-item">My Profile</a></div>
		<div class="popover-inner"><a class="btn" href="{% url 'core:logout' %}" class="list-group-item">Log out</a></div>
	</ul>
	{% endif %}
</div>

core/templates/layout/includes/sidebar.html
{% load staticfiles %}
<!-- Side navigation -->
<div class="sidenav center">
	<div class="logo center"><img src="{% static '/assets/img/icon/gmovies-logo.png' %}"></div><br>
	{% if 'user' in request.user.id|getPermissions|toStrArr or request.user.is_superuser %}
	<div class="nav user center"><a href="{% url 'user:user-list' %}"><div class="nav-inner{% if 'group' in request.get_full_path or 'user' in request.get_full_path or 'permission' in request.get_full_path  %} active {% endif %}"><img src="{% static '/assets/img/icon/ic-usermgmt.png' %}"><br>User Management</div></a></div>
	{% endif %}
	{% if 'transaction' in request.user.id|getPermissions|toStrArr or request.user.is_superuser %}
	<div class="nav transaction center"><a href="{% url 'transaction:transaction' %}"><div class="nav-inner{% if request.resolver_match.url_name == 'transaction' %} active {% endif %}"><img src="{% static '/assets/img/icon/ic-transaction-report.png' %}"><br>List of Entries</div></a></div>
	{% endif %}
</div>